# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0:

variables:
  ARCH_PKGS: 'xorg-util-macros autoconf automake make gettext pkg-config gcc grep m4 python'
  BUILDDIR: '_build'
  INSTDIR: '$CI_PROJECT_DIR/_inst'
  CONFIGURE_ARGS: ''
  MAKE_EXTRA_ARG: ''

# We use arch because the image updates frequently and we're not stuck
# forever in the update phase
.default_setup:
  image: archlinux/base
  before_script:
    - pacman -S --refresh
    - pacman -S --sysupgrade --noconfirm
    - pacman -S --noconfirm $ARCH_PKGS

.default_build:
  extends: .default_setup
  script:
   - rm -rf "$BUILDDIR"
   - mkdir -p "$BUILDDIR"
   - mkdir -p "$INSTDIR"
   - autoreconf -ivf
   - pushd "$BUILDDIR"
   - ../configure --prefix="$INSTDIR" --disable-silent-rules --disable-runtime-deps "$CONFIGURE_ARGS"
   - make
   - if test x"$MAKE_EXTRA_COMMAND" != "x"; then make $MAKE_EXTRA_COMMAND; fi

make_install:
  extends: .default_build
  stage: build
  variables:
      MAKE_EXTRA_COMMAND: "install"
  after_script:
    - pacman -S --noconfirm tree
    - tree $INSTDIR
  artifacts:
    name: installed files
    expire_in: 20 min
    paths:
      - $INSTDIR/

make_check:
  extends: .default_build
  stage: build
  variables:
      MAKE_EXTRA_COMMAND: "check"

make_distcheck:
  extends: .default_build
  stage: build
  variables:
      MAKE_EXTRA_COMMAND: "distcheck"

# download libxkbcommon and run its layout test program. This will
# run a basic keymap compile test against every combination of
# layout/variant/option. Syntax errors will fail the test, check the
# archived file for details.
layout_tests:
  extends: .default_setup
  stage: test
  needs: ["make_install"]
  script:
    - pacman -S --noconfirm git meson bison gcc
    - git clone https://github.com/xkbcommon/libxkbcommon
    - pushd libxkbcommon > /dev/null
    - meson builddir -Denable-wayland=false -Denable-x11=false -Denable-docs=false -Dxkb-config-root="$INSTDIR/share/X11/xkb"
    - ninja -C builddir
    - echo Running test script - this will take several minutes
    - ./builddir/xkeyboard-config-test > $INSTDIR/xkeyboard-config-test.out
    - popd > /dev/null
  variables:
    GIT_STRATEGY: none
  artifacts:
    name: xkeyboard-config test output
    expire_in: 2 weeks
    paths:
    - $INSTDIR/xkeyboard-config-test.out
