repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 23.12.0
  hooks:
  - id: black
    args: ['--check', '--diff', '.']
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.8
  hooks:
  - id: ruff
    args: ['--ignore=E741,E501', '.',]
